'use client'

import { useEffect, useState, useCallback } from 'react'
import Link from 'next/link'
import { allWords } from '@/lib/vocab'
import { loadStore } from '@/lib/localStore'
import {
  getMimoPlanSettings,
  getTodayMimoPlan,
  saveTodayMimoPlan,
  clearTodayMimoPlan,
  calculateDaysRemaining,
  calculateDailyNewWordTarget,
  buildLocalPlanCandidates,
  generateLocalFallbackPlan,
  validateAndCleanAiPlan,
  INTENSITY_LIMITS,
  todayStr,
} from '@/lib/mimoPlan'
import type { MimoDailyPlan } from '@/lib/types'

function StatPill({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div className="text-center">
      <p className={`text-lg font-bold ${color}`}>{value}</p>
      <p className="text-[10px] text-text-tertiary">{label}</p>
    </div>
  )
}

export default function MimoPlanCard() {
  const [plan, setPlan] = useState<MimoDailyPlan | null>(null)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const buildAndSavePlan = useCallback(async (forceAI = false): Promise<void> => {
    setError(null)
    setGenerating(true)
    try {
      const settings = getMimoPlanSettings()
      const store = loadStore()
      const pm = store.wordProgress

      // Stats
      const statuses = Object.values(pm)
      const learnedWords = statuses.filter(p => p.status !== 'unseen').length
      const masteredWords = statuses.filter(p => p.status === 'mastered').length
      const remainingWords = allWords.length - masteredWords
      const daysRemaining = calculateDaysRemaining(settings.targetDate)
      const { target: dailyNewTarget, warning } = calculateDailyNewWordTarget(
        allWords.length - learnedWords,
        daysRemaining,
        settings.dailyIntensity
      )

      const statsObj = {
        totalWords: allWords.length,
        learnedWords,
        masteredWords,
        remainingWords,
        daysRemaining,
        dailyNewTarget,
      }

      const candidates = buildLocalPlanCandidates(pm, allWords, settings)

      let resultPlan: MimoDailyPlan | null = null

      // Try AI if enabled and not suppressed
      if (settings.enabled) {
        try {
          const body = {
            date: todayStr(),
            targetDate: settings.targetDate,
            daysRemaining,
            totalWords: allWords.length,
            learnedWords,
            masteredWords,
            remainingWords,
            dailyNewTarget,
            intensity: settings.dailyIntensity,
            candidateNewWords: candidates.candidateNewWords,
            candidateReviewWords: candidates.candidateReviewWords,
            candidateWrongWords: candidates.candidateWrongWords,
            candidateFuzzyWords: candidates.candidateFuzzyWords,
          }
          const resp = await fetch('/api/mimo/plan', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
          })
          if (resp.ok) {
            const raw = await resp.json()
            if (raw && !raw.error) {
              const validIds = new Set(allWords.map(w => w.id))
              const limits = INTENSITY_LIMITS[settings.dailyIntensity]
              const cleaned = validateAndCleanAiPlan(raw, validIds, limits)
              if (cleaned && ((cleaned.newWordIds?.length ?? 0) + (cleaned.reviewWordIds?.length ?? 0)) > 0) {
                resultPlan = {
                  ...generateLocalFallbackPlan(settings, statsObj, candidates),
                  ...cleaned,
                  date: todayStr(),
                  targetDate: settings.targetDate,
                  daysRemaining,
                  totalWords: allWords.length,
                  learnedWords,
                  masteredWords,
                  remainingWords,
                  createdBy: 'mimo_ai',
                  createdAt: new Date().toISOString(),
                  updatedAt: new Date().toISOString(),
                }
              }
            }
          }
        } catch { /* fall through to local */ }
      }

      if (!resultPlan) {
        resultPlan = generateLocalFallbackPlan(settings, statsObj, candidates)
      }

      saveTodayMimoPlan(resultPlan)
      setPlan(resultPlan)
      if (warning) setError(warning)
    } catch (e) {
      setError(e instanceof Error ? e.message : '计划生成失败')
    } finally {
      setGenerating(false)
    }
  }, [])

  useEffect(() => {
    const settings = getMimoPlanSettings()
    if (!settings.enabled) return

    const existing = getTodayMimoPlan()
    if (existing) {
      setPlan(existing)
      return
    }

    if (settings.autoGenerateDailyPlan) {
      buildAndSavePlan()
    }
  }, [buildAndSavePlan])

  const handleRegenerate = () => {
    clearTodayMimoPlan()
    buildAndSavePlan(true)
  }

  const settings = getMimoPlanSettings()
  if (!settings.enabled) {
    return (
      <div className="bg-gradient-to-r from-accent/10 to-purple-100 rounded-xl p-4 mb-4 flex items-center justify-between">
        <div>
          <p className="text-sm font-semibold text-text-primary">Mimo AI 学习计划</p>
          <p className="text-xs text-text-secondary mt-0.5">开启后每天自动生成阅读词汇计划</p>
        </div>
        <Link href="/profile" className="px-3 py-1.5 bg-accent text-white rounded-lg text-xs font-medium active:scale-95 transition-all">
          去开启
        </Link>
      </div>
    )
  }

  if (generating) {
    return (
      <div className="bg-gradient-to-r from-accent to-purple-500 text-white rounded-xl p-4 mb-4">
        <div className="flex items-center gap-2">
          <div className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin flex-shrink-0" />
          <p className="text-sm font-semibold">Mimo AI 正在生成今日阅读词汇计划…</p>
        </div>
      </div>
    )
  }

  if (!plan) {
    return (
      <div className="bg-white rounded-xl shadow-card p-4 mb-4">
        <p className="text-sm font-semibold text-text-primary mb-2">Mimo AI 今日阅读词汇计划</p>
        <p className="text-xs text-text-secondary mb-3">今天还没有计划，点击生成</p>
        <button
          onClick={() => buildAndSavePlan()}
          className="w-full py-2.5 rounded-lg bg-accent text-white text-sm font-medium active:scale-[0.97] transition-all"
        >
          生成今日计划
        </button>
      </div>
    )
  }

  const totalTaskWords =
    plan.newWordIds.length +
    plan.reviewWordIds.length +
    plan.wrongWordIds.length +
    plan.fuzzyWordIds.length

  const progress = getTodayProgress()
  const doneCount = progress?.completedWordIds.length ?? 0
  const completionRate = totalTaskWords > 0 ? Math.round((doneCount / totalTaskWords) * 100) : 0

  return (
    <div className="bg-white rounded-xl shadow-card p-4 mb-4">
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className="text-base">🤖</span>
            <p className="text-sm font-bold text-text-primary">Mimo AI 今日阅读词汇计划</p>
          </div>
          <p className="text-xs text-text-secondary mt-0.5 leading-relaxed">{plan.planTitle}</p>
        </div>
        {plan.createdBy === 'local_fallback' && (
          <span className="text-[10px] text-text-tertiary bg-bg-tertiary px-1.5 py-0.5 rounded ml-2 flex-shrink-0">本地计划</span>
        )}
      </div>

      {/* AI summary */}
      <p className="text-xs text-text-secondary leading-relaxed mb-3 bg-accent/5 rounded-lg px-3 py-2">
        {plan.aiSummary}
      </p>

      {/* Progress bar */}
      {completionRate > 0 && (
        <div className="mb-3">
          <div className="flex justify-between text-[10px] text-text-tertiary mb-1">
            <span>今日完成进度</span>
            <span>{completionRate}%</span>
          </div>
          <div className="w-full bg-bg-tertiary rounded-full h-1.5">
            <div
              className="bg-accent h-1.5 rounded-full transition-all duration-500"
              style={{ width: `${completionRate}%` }}
            />
          </div>
        </div>
      )}

      {/* Stats */}
      <div className="grid grid-cols-5 gap-1 mb-3 bg-bg-primary rounded-xl p-2.5">
        <StatPill label="新词" value={plan.newWordIds.length} color="text-accent" />
        <StatPill label="复习" value={plan.reviewWordIds.length} color="text-blue-500" />
        <StatPill label="错词" value={plan.wrongWordIds.length} color="text-danger" />
        <StatPill label="模糊" value={plan.fuzzyWordIds.length} color="text-warning" />
        <StatPill label="约分钟" value={plan.estimatedMinutes} color="text-text-secondary" />
      </div>

      {/* Distance to goal */}
      <div className="flex items-center justify-between text-xs text-text-tertiary mb-3">
        <span>距目标 <strong className="text-text-primary">{plan.daysRemaining}</strong> 天</span>
        <span>剩余 <strong className="text-text-primary">{plan.remainingWords}</strong> 词</span>
      </div>

      {error && <p className="text-[10px] text-warning mb-2">⚠ {error}</p>}

      {/* Action buttons */}
      <div className="flex gap-2">
        <Link
          href="/daily-plan"
          className="flex-1 py-2.5 rounded-lg bg-accent text-white text-xs font-semibold text-center active:scale-[0.97] transition-all"
        >
          开始今日计划
        </Link>
        <button
          onClick={handleRegenerate}
          className="px-3 py-2.5 rounded-lg bg-bg-tertiary text-text-secondary text-xs font-medium active:scale-95 transition-all"
        >
          重新生成
        </button>
        <Link
          href="/profile"
          className="px-3 py-2.5 rounded-lg bg-bg-tertiary text-text-secondary text-xs font-medium active:scale-95 transition-all"
        >
          调整
        </Link>
      </div>
    </div>
  )
}

// Re-export helper needed by the card
function getTodayProgress() {
  if (typeof window === 'undefined') return null
  try {
    const raw = localStorage.getItem('mimoPlanHistory_v1')
    if (!raw) return null
    const all = JSON.parse(raw)
    const today = new Date().toISOString().slice(0, 10)
    return all[today] ?? null
  } catch { return null }
}
