import type {
  MimoPlanSettings,
  MimoDailyPlan,
  MimoPlanProgress,
  MimoIntensity,
  MimoTargetMode,
  WordStatus,
  FrequencyLevel,
} from './types'
import type { VocabWord } from './types'
import { getLocalDateString } from './date'

// ── Storage keys ──────────────────────────────────────────────────────────────
const SETTINGS_KEY = 'mimoPlanSettings_v1'
const PLAN_KEY = 'mimoDailyPlan_v1'
const PROGRESS_KEY = 'mimoPlanHistory_v1'

// ── Intensity limits ──────────────────────────────────────────────────────────
export const INTENSITY_LIMITS: Record<MimoIntensity, {
  newWords: number; reviewWords: number; minMin: number; maxMin: number
}> = {
  easy:   { newWords: 15,  reviewWords: 30,  minMin: 10, maxMin: 15 },
  normal: { newWords: 30,  reviewWords: 60,  minMin: 20, maxMin: 30 },
  sprint: { newWords: 60,  reviewWords: 120, minMin: 40, maxMin: 60 },
}

// ── Frequency priority (lower = higher priority) ──────────────────────────────
const FREQ_PRIORITY: Record<string, number> = {
  '高频': 0, '中频': 1, '低频': 2, '超纲拓展': 3,
}
function freqScore(f: FrequencyLevel | undefined | null): number {
  return f ? (FREQ_PRIORITY[f] ?? 4) : 4
}

// ── Candidate word shape sent to AI ──────────────────────────────────────────
export interface CandidateWord {
  id: string
  word: string
  meaning: string
  level: string
  frequencyLevel: FrequencyLevel | null
  status: WordStatus
  wrongCount: number
  fuzzyCount: number
  nextReviewAt: string | null
  isWrongWord: boolean
}

// ── Date helpers ──────────────────────────────────────────────────────────────
// Use local timezone date to avoid UTC date-shift for Taiwan (UTC+8) users.
export function todayStr(): string {
  return getLocalDateString()
}

export function addDays(base: string, days: number): string {
  const d = new Date(base + 'T00:00:00')
  d.setDate(d.getDate() + days)
  return getLocalDateString(d)
}

export function calculateDaysRemaining(targetDate: string | null): number {
  if (!targetDate) return 90
  const today = new Date(todayStr() + 'T00:00:00')
  const target = new Date(targetDate + 'T00:00:00')
  const diff = Math.ceil((target.getTime() - today.getTime()) / 86400000)
  return Math.max(1, diff)
}

export function getTargetDateFromMode(mode: MimoTargetMode): string | null {
  const daysMap: Record<string, number> = {
    '30_days': 30, '60_days': 60, '90_days': 90, '120_days': 120,
  }
  const days = daysMap[mode]
  if (!days) return null
  return addDays(todayStr(), days)
}

// ── Settings ──────────────────────────────────────────────────────────────────
export function getDefaultSettings(): MimoPlanSettings {
  return {
    enabled: true,
    targetMode: '90_days',
    targetDate: addDays(todayStr(), 90),
    dailyIntensity: 'normal',
    preferHighFrequency: true,
    preferWrongWords: true,
    autoGenerateDailyPlan: true,
    updatedAt: new Date().toISOString(),
    // Extended settings
    dailyNewWordsMode: 'auto',
    dailyNewWords: 20,
    dailyReviewLimit: 60,
    dailyMinutes: 30,
    allowAiAdjust: true,
  }
}

export function getMimoPlanSettings(): MimoPlanSettings {
  if (typeof window === 'undefined') return getDefaultSettings()
  try {
    const raw = localStorage.getItem(SETTINGS_KEY)
    if (!raw) return getDefaultSettings()
    return { ...getDefaultSettings(), ...JSON.parse(raw) }
  } catch { return getDefaultSettings() }
}

export function saveMimoPlanSettings(s: MimoPlanSettings): void {
  if (typeof window === 'undefined') return
  try {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify({ ...s, updatedAt: new Date().toISOString() }))
  } catch {}
}

// ── Daily plan storage ────────────────────────────────────────────────────────
export function getTodayMimoPlan(): MimoDailyPlan | null {
  if (typeof window === 'undefined') return null
  try {
    const raw = localStorage.getItem(PLAN_KEY)
    if (!raw) return null
    const plan: MimoDailyPlan = JSON.parse(raw)
    if (plan.date !== todayStr()) return null  // stale
    return plan
  } catch { return null }
}

export function saveTodayMimoPlan(plan: MimoDailyPlan): void {
  if (typeof window === 'undefined') return
  try { localStorage.setItem(PLAN_KEY, JSON.stringify(plan)) } catch {}
}

export function clearTodayMimoPlan(): void {
  if (typeof window === 'undefined') return
  try { localStorage.removeItem(PLAN_KEY) } catch {}
}

// ── Progress storage ──────────────────────────────────────────────────────────
export function getTodayProgress(): MimoPlanProgress | null {
  if (typeof window === 'undefined') return null
  try {
    const raw = localStorage.getItem(PROGRESS_KEY)
    if (!raw) return null
    const all: Record<string, MimoPlanProgress> = JSON.parse(raw)
    return all[todayStr()] ?? null
  } catch { return null }
}

export function saveTodayProgress(p: MimoPlanProgress): void {
  if (typeof window === 'undefined') return
  try {
    const raw = localStorage.getItem(PROGRESS_KEY)
    const all: Record<string, MimoPlanProgress> = raw ? JSON.parse(raw) : {}
    all[p.date] = p
    // keep last 30 days only
    const keys = Object.keys(all).sort().slice(-30)
    const pruned: Record<string, MimoPlanProgress> = {}
    keys.forEach(k => { pruned[k] = all[k] })
    localStorage.setItem(PROGRESS_KEY, JSON.stringify(pruned))
  } catch {}
}

// ── Daily new-word target ──────────────────────────────────────────────────────
export function calculateDailyNewWordTarget(
  remainingUnlearned: number,
  daysRemaining: number,
  intensity: MimoIntensity,
  mode: 'auto' | 'manual' = 'auto',
  manualTarget?: number
): { target: number; capped: boolean; warning: string | null } {
  if (mode === 'manual' && manualTarget !== undefined && manualTarget > 0) {
    let warning: string | null = null
    if (manualTarget > 200) {
      warning = `每天 ${manualTarget} 个新词强度很高，可能需要较长学习时间，但系统会按你的目标生成计划。`
    } else if (manualTarget > 100) {
      warning = `按当前目标需要每天新学约 ${manualTarget} 个词，任务量较大，建议确认是否要冲刺完成。`
    }
    return { target: manualTarget, capped: false, warning }
  }

  // Auto mode: directly calculate from remaining/days
  const raw = Math.ceil(remainingUnlearned / Math.max(1, daysRemaining))
  let warning: string | null = null
  if (raw > 200) {
    warning = `按当前目标每天需新学约 ${raw} 个词，强度很高，系统会按目标生成计划，建议确认是否要冲刺完成。`
  } else if (raw > 100) {
    warning = `按当前目标需要每天新学约 ${raw} 个词，任务量较大，建议确认是否要冲刺完成。`
  }
  // intensity is kept in the signature for call-site compatibility;
  // it no longer caps new-word count (only review limits and minutes).
  return { target: raw, capped: false, warning }
}

// ── Sentence meaning target count (dynamic based on new-word count) ───────────
export function getSentenceMeaningTargetCount(newWordCount: number): number {
  if (newWordCount <= 50) return Math.min(newWordCount, 10)
  if (newWordCount <= 150) return 20
  if (newWordCount <= 300) return 35
  return 50
}

// ── Build local candidate word lists ─────────────────────────────────────────
export function buildLocalPlanCandidates(
  wordProgress: Record<string, {
    status: WordStatus
    wrongCount: number
    fuzzyCount: number
    quizWrongCount: number
    nextReviewAt: string | null
    isWrongWord: boolean
  }>,
  words: VocabWord[],
  settings: MimoPlanSettings,
  dailyNewTarget?: number
): {
  candidateNewWords: CandidateWord[]
  candidateReviewWords: CandidateWord[]
  candidateWrongWords: CandidateWord[]
  candidateFuzzyWords: CandidateWord[]
} {
  const now = new Date()
  const toCandidate = (w: VocabWord): CandidateWord => {
    const p = wordProgress[w.id]
    return {
      id: w.id,
      word: w.word,
      meaning: w.meaning,
      level: w.level,
      frequencyLevel: w.frequencyLevel ?? null,
      status: p?.status ?? 'unseen',
      wrongCount: (p?.wrongCount ?? 0) + (p?.quizWrongCount ?? 0),
      fuzzyCount: p?.fuzzyCount ?? 0,
      nextReviewAt: p?.nextReviewAt ?? null,
      isWrongWord: p?.isWrongWord ?? false,
    }
  }

  const isDue = (nextReviewAt: string | null) =>
    !nextReviewAt || new Date(nextReviewAt) <= now

  const sortByFreq = (a: CandidateWord, b: CandidateWord) =>
    freqScore(a.frequencyLevel) - freqScore(b.frequencyLevel) ||
    b.wrongCount - a.wrongCount

  const newWords: CandidateWord[] = []
  const reviewWords: CandidateWord[] = []
  const wrongWords: CandidateWord[] = []
  const fuzzyWords: CandidateWord[] = []

  for (const w of words) {
    const c = toCandidate(w)
    if (c.status === 'unseen') {
      newWords.push(c)
    } else if (c.status === 'mastered') {
      // skip mastered words as new words
    } else {
      if (c.isWrongWord || c.wrongCount > 0) wrongWords.push(c)
      if (c.status === 'fuzzy' || c.fuzzyCount > 0) fuzzyWords.push(c)
      if (isDue(c.nextReviewAt)) reviewWords.push(c)
    }
  }

  // Sort: high frequency + wrong count first
  newWords.sort(sortByFreq)
  reviewWords.sort((a, b) => sortByFreq(a, b))
  wrongWords.sort((a, b) => b.wrongCount - a.wrongCount || freqScore(a.frequencyLevel) - freqScore(b.frequencyLevel))
  fuzzyWords.sort((a, b) => b.fuzzyCount - a.fuzzyCount || freqScore(a.frequencyLevel) - freqScore(b.frequencyLevel))

  // Dynamic pool: cover the daily target with a 20% buffer (min 120, max all unseen)
  const needed = dailyNewTarget ?? 120
  const newWordPoolSize = Math.min(newWords.length, Math.ceil(needed * 1.2) + 20)

  return {
    candidateNewWords:    newWords.slice(0, Math.max(120, newWordPoolSize)),
    candidateReviewWords: reviewWords.slice(0, 200),
    candidateWrongWords:  wrongWords,
    candidateFuzzyWords:  fuzzyWords,
  }
}

// ── Local fallback plan (no AI needed) ───────────────────────────────────────
export function generateLocalFallbackPlan(
  settings: MimoPlanSettings,
  stats: {
    totalWords: number; learnedWords: number; masteredWords: number
    remainingWords: number; daysRemaining: number; dailyNewTarget: number
  },
  candidates: ReturnType<typeof buildLocalPlanCandidates>,
  allVocabWords?: VocabWord[]
): MimoDailyPlan {
  const limits = INTENSITY_LIMITS[settings.dailyIntensity]
  const now = new Date().toISOString()

  const effectiveNewTarget: number = settings.dailyNewWordsMode === 'manual'
    ? settings.dailyNewWords
    : stats.dailyNewTarget

  // Effective review cap: respect user's dailyReviewLimit and intensity
  const effectiveReviewCap = Math.min(settings.dailyReviewLimit, limits.reviewWords)

  const newIds = candidates.candidateNewWords
    .slice(0, effectiveNewTarget)
    .map(w => w.id)

  // Wrong/fuzzy: proportional to review cap, not fixed 10
  const wrongTarget = Math.min(
    candidates.candidateWrongWords.length,
    Math.max(10, Math.floor(effectiveReviewCap * 0.25)),
    50
  )
  const fuzzyTarget = Math.min(
    candidates.candidateFuzzyWords.length,
    Math.max(10, Math.floor(effectiveReviewCap * 0.25)),
    50
  )

  const wrongIds = candidates.candidateWrongWords
    .slice(0, wrongTarget)
    .map(w => w.id)

  const fuzzyIds = candidates.candidateFuzzyWords
    .filter(w => !wrongIds.includes(w.id))
    .slice(0, fuzzyTarget)
    .map(w => w.id)

  const usedIds = new Set([...newIds, ...wrongIds, ...fuzzyIds])
  const reviewIds = candidates.candidateReviewWords
    .filter(w => !usedIds.has(w.id))
    .slice(0, effectiveReviewCap)
    .map(w => w.id)

  // sentence-meaning: dynamic count based on new word count
  const sentenceTarget = getSentenceMeaningTargetCount(newIds.length)
  const sentenceIds = buildSentenceMeaningIds(
    candidates.candidateNewWords,
    candidates.candidateWrongWords,
    sentenceTarget,
    allVocabWords
  )

  const estimatedMin = Math.round(
    (newIds.length * 1.5 + reviewIds.length * 0.5 + wrongIds.length * 1.0 + sentenceIds.length * 0.3)
  )

  const intensityLabel =
    settings.dailyIntensity === 'easy' ? '轻松' :
    settings.dailyIntensity === 'normal' ? '标准' : '冲刺'

  return {
    date: todayStr(),
    planTitle: `高频阅读识词 + ${wrongIds.length > 0 ? '错词重认' : '到期复习'}`,
    aiSummary: `今天建议先拿下 ${newIds.length} 个新词，再复习 ${reviewIds.length} 个到期词${wrongIds.length > 0 ? `，重点重认 ${wrongIds.length} 个错词` : ''}。目标是高考阅读快速识义，不要求拼写。`,
    targetDate: settings.targetDate,
    daysRemaining: stats.daysRemaining,
    totalWords: stats.totalWords,
    learnedWords: stats.learnedWords,
    masteredWords: stats.masteredWords,
    remainingWords: stats.remainingWords,
    newWordIds: newIds,
    reviewWordIds: reviewIds,
    wrongWordIds: wrongIds,
    fuzzyWordIds: fuzzyIds,
    sentenceMeaningWordIds: sentenceIds,
    confusingWordIds: [],
    estimatedMinutes: Math.max(limits.minMin, estimatedMin),
    priorityReason: `${intensityLabel}模式：优先高频词 + 错词，以阅读识义为主`,
    motivationalMessage: `距目标还剩 ${stats.daysRemaining} 天，剩余 ${stats.remainingWords} 词，继续加油！`,
    createdBy: 'local_fallback',
    createdAt: now,
    updatedAt: now,
  }
}

// ── Build sentence-meaning word IDs ───────────────────────────────────────────
// Prioritizes high-freq new words with examples/gaokaoExamples.
// Falls back to any new word with examples, then wrong words with examples.
export function buildSentenceMeaningIds(
  candidateNewWords: CandidateWord[],
  candidateWrongWords: CandidateWord[],
  target: number,
  allVocabWords?: VocabWord[]
): string[] {
  if (target <= 0) return []

  // Build a lookup for vocab details (has examples?)
  const vocabMap = new Map<string, VocabWord>()
  if (allVocabWords) {
    for (const w of allVocabWords) vocabMap.set(w.id, w)
  }

  const hasExamples = (id: string): boolean => {
    const v = vocabMap.get(id)
    if (!v) return true // assume yes if no vocab map available
    return (v.gaokaoExamples?.length ?? 0) > 0 || (v.examples?.length ?? 0) > 0
  }

  const picked = new Set<string>()

  // Tier 1: high-freq new words with examples
  for (const w of candidateNewWords) {
    if (picked.size >= target) break
    if (w.frequencyLevel === '高频' && hasExamples(w.id)) picked.add(w.id)
  }

  // Tier 2: any new word with examples
  for (const w of candidateNewWords) {
    if (picked.size >= target) break
    if (!picked.has(w.id) && hasExamples(w.id)) picked.add(w.id)
  }

  // Tier 3: wrong words with examples (supplement only)
  const wrongBudget = Math.floor(target * 0.2)
  let wrongAdded = 0
  for (const w of candidateWrongWords) {
    if (picked.size >= target || wrongAdded >= wrongBudget) break
    if (!picked.has(w.id) && hasExamples(w.id)) {
      picked.add(w.id)
      wrongAdded++
    }
  }

  // Tier 4: any remaining new words (no example filter)
  for (const w of candidateNewWords) {
    if (picked.size >= target) break
    if (!picked.has(w.id)) picked.add(w.id)
  }

  return Array.from(picked).slice(0, target)
}

// ── Enforce new-word count target after merging AI result ─────────────────────
// allowAiAdjust only affects AI ordering / prioritization, NOT the total count.
// Both auto and manual modes strictly enforce target count:
//   - trim if AI returned more than targetCount
//   - supplement from candidateNewWords if AI returned too few
// Returns actual candidates if pool is exhausted (with fewer than target).
export function enforceTargetNewWordCount(
  aiNewWordIds: string[],
  targetCount: number,
  candidateNewWords: CandidateWord[],
  _allowAiAdjust: boolean  // kept for API compatibility; no longer grants count slack
): string[] {
  // Trim excess
  const trimmed = aiNewWordIds.length > targetCount
    ? aiNewWordIds.slice(0, targetCount)
    : aiNewWordIds

  if (trimmed.length >= targetCount) return trimmed

  // Supplement from local candidate pool to strictly reach target
  const existing = new Set(trimmed)
  const extra = candidateNewWords
    .filter(w => !existing.has(w.id))
    .slice(0, targetCount - trimmed.length)
    .map(w => w.id)
  return [...trimmed, ...extra]
}

// Kept for backward compatibility — delegates to enforceTargetNewWordCount.
export function enforceUserNewWordCount(
  aiNewWordIds: string[],
  settings: MimoPlanSettings,
  candidateNewWords: CandidateWord[]
): string[] {
  if (settings.dailyNewWordsMode !== 'manual') return aiNewWordIds
  return enforceTargetNewWordCount(
    aiNewWordIds,
    settings.dailyNewWords,
    candidateNewWords,
    settings.allowAiAdjust
  )
}

// ── Compute effective limits that respect user settings ───────────────────────
export interface IntensityLimit { newWords: number; reviewWords: number; minMin: number; maxMin: number }

export function getEffectiveLimits(
  settings: MimoPlanSettings,
  dailyNewTarget?: number
): IntensityLimit {
  const base = INTENSITY_LIMITS[settings.dailyIntensity]
  const effectiveNew = settings.dailyNewWordsMode === 'manual'
    ? settings.dailyNewWords
    : (dailyNewTarget ?? base.newWords)
  const effectiveReview = Math.min(settings.dailyReviewLimit, base.reviewWords)
  return { ...base, newWords: effectiveNew, reviewWords: effectiveReview }
}

// ── Enforce sentence meaning word IDs after AI response ──────────────────────
export function enforceSentenceMeaningWordIds(
  aiIds: string[],
  target: number,
  candidateNewWords: CandidateWord[],
  candidateWrongWords: CandidateWord[],
  validIds: Set<string>,
  allVocabWords?: VocabWord[]
): string[] {
  // Filter to valid IDs first
  const filtered = aiIds.filter(id => validIds.has(id))

  if (filtered.length >= target) return filtered.slice(0, target)

  // Supplement using local rule
  const localIds = buildSentenceMeaningIds(
    candidateNewWords,
    candidateWrongWords,
    target,
    allVocabWords
  )
  const existing = new Set(filtered)
  const extra = localIds.filter(id => !existing.has(id)).slice(0, target - filtered.length)
  return [...filtered, ...extra].slice(0, target)
}

// ── Validate and clean AI response ────────────────────────────────────────────
export function validateAndCleanAiPlan(
  raw: Record<string, unknown>,
  validIds: Set<string>,
  limits: IntensityLimit
): Partial<MimoDailyPlan> | null {
  const filterIds = (arr: unknown, cap: number): string[] => {
    if (!Array.isArray(arr)) return []
    return (arr as string[]).filter(id => typeof id === 'string' && validIds.has(id)).slice(0, cap)
  }

  const newIds = filterIds(raw.newWordIds, limits.newWords)
  if (newIds.length === 0 && !raw.reviewWordIds) return null  // completely empty

  // wrong/fuzzy: use large caps here; callers will apply real limits based on candidates
  return {
    planTitle: typeof raw.planTitle === 'string' ? raw.planTitle : '今日阅读词汇计划',
    aiSummary: typeof raw.aiSummary === 'string' ? raw.aiSummary : '',
    newWordIds: newIds,
    reviewWordIds: filterIds(raw.reviewWordIds, limits.reviewWords),
    wrongWordIds: filterIds(raw.wrongWordIds, 100),
    fuzzyWordIds: filterIds(raw.fuzzyWordIds, 100),
    sentenceMeaningWordIds: filterIds(raw.sentenceMeaningWordIds, 100),
    confusingWordIds: filterIds(raw.confusingWordIds, 100),
    estimatedMinutes: typeof raw.estimatedMinutes === 'number' ? raw.estimatedMinutes : limits.minMin,
    priorityReason: typeof raw.priorityReason === 'string' ? raw.priorityReason : '',
    motivationalMessage: typeof raw.motivationalMessage === 'string' ? raw.motivationalMessage : '',
  }
}

// ── Enforce wrong/fuzzy counts based on actual candidates ────────────────────
export function enforceWrongFuzzyWordIds(
  aiWrongIds: string[],
  aiFuzzyIds: string[],
  candidateWrongWords: CandidateWord[],
  candidateFuzzyWords: CandidateWord[],
  dailyReviewLimit: number,
  validIds: Set<string>
): { wrongWordIds: string[]; fuzzyWordIds: string[] } {
  const candidateWrongIds = candidateWrongWords.map(w => w.id)
  const candidateFuzzyIds = candidateFuzzyWords.map(w => w.id)

  const wrongTarget = Math.min(
    candidateWrongWords.length,
    Math.max(10, Math.floor(dailyReviewLimit * 0.25)),
    50
  )
  const fuzzyTarget = Math.min(
    candidateFuzzyWords.length,
    Math.max(10, Math.floor(dailyReviewLimit * 0.25)),
    50
  )

  // Filter AI IDs to only valid candidates
  const filteredWrong = aiWrongIds.filter(id => validIds.has(id) && candidateWrongIds.includes(id))
  const filteredFuzzy = aiFuzzyIds.filter(id => validIds.has(id) && candidateFuzzyIds.includes(id))

  // Supplement from candidates if AI returned too few
  const wrongSet = new Set(filteredWrong)
  const extraWrong = candidateWrongIds
    .filter(id => !wrongSet.has(id))
    .slice(0, wrongTarget - filteredWrong.length)
  const wrongWordIds = [...filteredWrong, ...extraWrong].slice(0, wrongTarget)

  const fuzzySet = new Set([...filteredFuzzy, ...wrongWordIds])
  const extraFuzzy = candidateFuzzyIds
    .filter(id => !fuzzySet.has(id))
    .slice(0, fuzzyTarget - filteredFuzzy.length)
  const fuzzyWordIds = [...filteredFuzzy, ...extraFuzzy].slice(0, fuzzyTarget)

  return { wrongWordIds, fuzzyWordIds }
}
