import type {
  MimoPlanSettings,
  MimoDailyPlan,
  MimoPlanProgress,
  MimoIntensity,
  MimoTargetMode,
  WordStatus,
  FrequencyLevel,
} from './types'
import type { VocabWord } from './types'

// ── Storage keys ──────────────────────────────────────────────────────────────
const SETTINGS_KEY = 'mimoPlanSettings_v1'
const PLAN_KEY = 'mimoDailyPlan_v1'
const PROGRESS_KEY = 'mimoPlanHistory_v1'

// ── Intensity limits ──────────────────────────────────────────────────────────
export const INTENSITY_LIMITS: Record<MimoIntensity, {
  newWords: number; reviewWords: number; minMin: number; maxMin: number
}> = {
  easy:   { newWords: 15,  reviewWords: 30,  minMin: 10, maxMin: 15 },
  normal: { newWords: 30,  reviewWords: 60,  minMin: 20, maxMin: 30 },
  sprint: { newWords: 60,  reviewWords: 120, minMin: 40, maxMin: 60 },
}

// ── Frequency priority (lower = higher priority) ──────────────────────────────
const FREQ_PRIORITY: Record<string, number> = {
  '高频': 0, '中频': 1, '低频': 2, '超纲拓展': 3,
}
function freqScore(f: FrequencyLevel | undefined | null): number {
  return f ? (FREQ_PRIORITY[f] ?? 4) : 4
}

// ── Candidate word shape sent to AI ──────────────────────────────────────────
export interface CandidateWord {
  id: string
  word: string
  meaning: string
  level: string
  frequencyLevel: FrequencyLevel | null
  status: WordStatus
  wrongCount: number
  fuzzyCount: number
  nextReviewAt: string | null
  isWrongWord: boolean
}

// ── Date helpers ──────────────────────────────────────────────────────────────
export function todayStr(): string {
  return new Date().toISOString().slice(0, 10)
}

export function addDays(base: string, days: number): string {
  const d = new Date(base)
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

export function calculateDaysRemaining(targetDate: string | null): number {
  if (!targetDate) return 90
  const today = new Date(todayStr())
  const target = new Date(targetDate)
  const diff = Math.ceil((target.getTime() - today.getTime()) / 86400000)
  return Math.max(1, diff)
}

export function getTargetDateFromMode(mode: MimoTargetMode): string | null {
  const daysMap: Record<string, number> = {
    '30_days': 30, '60_days': 60, '90_days': 90, '120_days': 120,
  }
  const days = daysMap[mode]
  if (!days) return null
  return addDays(todayStr(), days)
}

// ── Settings ──────────────────────────────────────────────────────────────────
export function getDefaultSettings(): MimoPlanSettings {
  return {
    enabled: true,
    targetMode: '90_days',
    targetDate: addDays(todayStr(), 90),
    dailyIntensity: 'normal',
    preferHighFrequency: true,
    preferWrongWords: true,
    autoGenerateDailyPlan: true,
    updatedAt: new Date().toISOString(),
    // Extended settings
    dailyNewWordsMode: 'auto',
    dailyNewWords: 20,
    dailyReviewLimit: 60,
    dailyMinutes: 30,
    allowAiAdjust: true,
  }
}

export function getMimoPlanSettings(): MimoPlanSettings {
  if (typeof window === 'undefined') return getDefaultSettings()
  try {
    const raw = localStorage.getItem(SETTINGS_KEY)
    if (!raw) return getDefaultSettings()
    return { ...getDefaultSettings(), ...JSON.parse(raw) }
  } catch { return getDefaultSettings() }
}

export function saveMimoPlanSettings(s: MimoPlanSettings): void {
  if (typeof window === 'undefined') return
  try {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify({ ...s, updatedAt: new Date().toISOString() }))
  } catch {}
}

// ── Daily plan storage ────────────────────────────────────────────────────────
export function getTodayMimoPlan(): MimoDailyPlan | null {
  if (typeof window === 'undefined') return null
  try {
    const raw = localStorage.getItem(PLAN_KEY)
    if (!raw) return null
    const plan: MimoDailyPlan = JSON.parse(raw)
    if (plan.date !== todayStr()) return null  // stale
    return plan
  } catch { return null }
}

export function saveTodayMimoPlan(plan: MimoDailyPlan): void {
  if (typeof window === 'undefined') return
  try { localStorage.setItem(PLAN_KEY, JSON.stringify(plan)) } catch {}
}

export function clearTodayMimoPlan(): void {
  if (typeof window === 'undefined') return
  try { localStorage.removeItem(PLAN_KEY) } catch {}
}

// ── Progress storage ──────────────────────────────────────────────────────────
export function getTodayProgress(): MimoPlanProgress | null {
  if (typeof window === 'undefined') return null
  try {
    const raw = localStorage.getItem(PROGRESS_KEY)
    if (!raw) return null
    const all: Record<string, MimoPlanProgress> = JSON.parse(raw)
    return all[todayStr()] ?? null
  } catch { return null }
}

export function saveTodayProgress(p: MimoPlanProgress): void {
  if (typeof window === 'undefined') return
  try {
    const raw = localStorage.getItem(PROGRESS_KEY)
    const all: Record<string, MimoPlanProgress> = raw ? JSON.parse(raw) : {}
    all[p.date] = p
    // keep last 30 days only
    const keys = Object.keys(all).sort().slice(-30)
    const pruned: Record<string, MimoPlanProgress> = {}
    keys.forEach(k => { pruned[k] = all[k] })
    localStorage.setItem(PROGRESS_KEY, JSON.stringify(pruned))
  } catch {}
}

// ── Daily new-word target ──────────────────────────────────────────────────────
// Intensity no longer caps new-word count. Intensity only affects review limits
// and estimated minutes. New-word count is driven by target date or manual input.
export function calculateDailyNewWordTarget(
  remainingUnlearned: number,
  daysRemaining: number,
  intensity: MimoIntensity,
  mode: 'auto' | 'manual' = 'auto',
  manualTarget?: number
): { target: number; capped: boolean; warning: string | null } {
  if (mode === 'manual' && manualTarget !== undefined && manualTarget > 0) {
    let warning: string | null = null
    if (manualTarget > 200) {
      warning = `每天 ${manualTarget} 个新词强度很高，可能需要较长学习时间，但系统会按你的目标生成计划。`
    } else if (manualTarget > 100) {
      warning = `按当前目标需要每天新学约 ${manualTarget} 个词，任务量较大，建议确认是否要冲刺完成。`
    }
    return { target: manualTarget, capped: false, warning }
  }

  // Auto mode: directly calculate from remaining/days, no intensity cap on new words
  const raw = Math.ceil(remainingUnlearned / Math.max(1, daysRemaining))
  let warning: string | null = null
  if (raw > 200) {
    warning = `按当前目标每天需新学约 ${raw} 个词，强度很高，系统会按目标生成计划，建议确认是否要冲刺完成。`
  } else if (raw > 100) {
    warning = `按当前目标需要每天新学约 ${raw} 个词，任务量较大，建议确认是否要冲刺完成。`
  }
  // intensity is kept in the signature for call-site compatibility;
  // it no longer caps new-word count (only review limits and minutes).
  return { target: raw, capped: false, warning }
}

// ── Build local candidate word lists ─────────────────────────────────────────
// Returns prioritised candidate lists sized to cover the effective daily target.
// The local-fallback pool is large enough to satisfy even high targets; callers
// should cap what they send to the AI separately (see AI_CANDIDATE_CAP).
export function buildLocalPlanCandidates(
  wordProgress: Record<string, {
    status: WordStatus
    wrongCount: number
    fuzzyCount: number
    quizWrongCount: number
    nextReviewAt: string | null
    isWrongWord: boolean
  }>,
  words: VocabWord[],
  settings: MimoPlanSettings,
  dailyNewTarget?: number   // effective new-word target for dynamic pool sizing
): {
  candidateNewWords: CandidateWord[]
  candidateReviewWords: CandidateWord[]
  candidateWrongWords: CandidateWord[]
  candidateFuzzyWords: CandidateWord[]
} {
  const now = new Date()
  const toCandidate = (w: VocabWord): CandidateWord => {
    const p = wordProgress[w.id]
    return {
      id: w.id,
      word: w.word,
      meaning: w.meaning,
      level: w.level,
      frequencyLevel: w.frequencyLevel ?? null,
      status: p?.status ?? 'unseen',
      wrongCount: (p?.wrongCount ?? 0) + (p?.quizWrongCount ?? 0),
      fuzzyCount: p?.fuzzyCount ?? 0,
      nextReviewAt: p?.nextReviewAt ?? null,
      isWrongWord: p?.isWrongWord ?? false,
    }
  }

  const isDue = (nextReviewAt: string | null) =>
    !nextReviewAt || new Date(nextReviewAt) <= now

  const sortByFreq = (a: CandidateWord, b: CandidateWord) =>
    freqScore(a.frequencyLevel) - freqScore(b.frequencyLevel) ||
    b.wrongCount - a.wrongCount

  const newWords: CandidateWord[] = []
  const reviewWords: CandidateWord[] = []
  const wrongWords: CandidateWord[] = []
  const fuzzyWords: CandidateWord[] = []

  for (const w of words) {
    const c = toCandidate(w)
    if (c.status === 'unseen') {
      newWords.push(c)
    } else if (c.status === 'mastered') {
      // skip mastered words as new words
    } else {
      if (c.isWrongWord || c.wrongCount > 0) wrongWords.push(c)
      if (c.status === 'fuzzy' || c.fuzzyCount > 0) fuzzyWords.push(c)
      if (isDue(c.nextReviewAt)) reviewWords.push(c)
    }
  }

  // Sort: high frequency + wrong count first
  newWords.sort(sortByFreq)
  reviewWords.sort((a, b) => sortByFreq(a, b))
  wrongWords.sort((a, b) => b.wrongCount - a.wrongCount || freqScore(a.frequencyLevel) - freqScore(b.frequencyLevel))
  fuzzyWords.sort((a, b) => b.fuzzyCount - a.fuzzyCount || freqScore(a.frequencyLevel) - freqScore(b.frequencyLevel))

  // Dynamic pool: cover the daily target with a 20% buffer (min 120, max all unseen)
  const needed = dailyNewTarget ?? 120
  const newWordPoolSize = Math.min(newWords.length, Math.ceil(needed * 1.2) + 20)

  return {
    candidateNewWords:    newWords.slice(0, Math.max(120, newWordPoolSize)),
    candidateReviewWords: reviewWords.slice(0, 150),
    candidateWrongWords:  wrongWords.slice(0, 50),
    candidateFuzzyWords:  fuzzyWords.slice(0, 50),
  }
}

// ── Local fallback plan (no AI needed) ───────────────────────────────────────
export function generateLocalFallbackPlan(
  settings: MimoPlanSettings,
  stats: {
    totalWords: number; learnedWords: number; masteredWords: number
    remainingWords: number; daysRemaining: number; dailyNewTarget: number
  },
  candidates: ReturnType<typeof buildLocalPlanCandidates>
): MimoDailyPlan {
  const limits = INTENSITY_LIMITS[settings.dailyIntensity]
  const now = new Date().toISOString()

  // Resolve effective new-word count based on mode
  // Intensity no longer caps new words — it only affects review limits and minutes.
  const effectiveNewTarget: number = settings.dailyNewWordsMode === 'manual'
    ? settings.dailyNewWords
    : stats.dailyNewTarget  // use the calculated target directly

  // Effective review cap: respect user's dailyReviewLimit and intensity
  const effectiveReviewCap = Math.min(settings.dailyReviewLimit, limits.reviewWords)

  const newIds = candidates.candidateNewWords
    .slice(0, effectiveNewTarget)
    .map(w => w.id)

  const wrongIds = candidates.candidateWrongWords
    .slice(0, Math.min(10, Math.floor(effectiveReviewCap * 0.2)))
    .map(w => w.id)

  const fuzzyIds = candidates.candidateFuzzyWords
    .filter(w => !wrongIds.includes(w.id))
    .slice(0, Math.min(10, Math.floor(effectiveReviewCap * 0.15)))
    .map(w => w.id)

  const usedIds = new Set([...newIds, ...wrongIds, ...fuzzyIds])
  const reviewIds = candidates.candidateReviewWords
    .filter(w => !usedIds.has(w.id))
    .slice(0, effectiveReviewCap)
    .map(w => w.id)

  // sentence-meaning: take from wrong + high-freq new
  const sentenceIds = [
    ...candidates.candidateWrongWords.slice(0, 5),
    ...candidates.candidateNewWords.filter(w => w.frequencyLevel === '高频').slice(0, 5),
  ].filter((w, i, arr) => arr.findIndex(x => x.id === w.id) === i)
    .slice(0, 10)
    .map(w => w.id)

  const estimatedMin = Math.round(
    (newIds.length * 1.5 + reviewIds.length * 0.5 + wrongIds.length * 1.0)
  )

  const intensityLabel =
    settings.dailyIntensity === 'easy' ? '轻松' :
    settings.dailyIntensity === 'normal' ? '标准' : '冲刺'

  return {
    date: todayStr(),
    planTitle: `高频阅读识词 + ${wrongIds.length > 0 ? '错词重认' : '到期复习'}`,
    aiSummary: `今天建议先拿下 ${newIds.length} 个新词，再复习 ${reviewIds.length} 个到期词${wrongIds.length > 0 ? `，重点重认 ${wrongIds.length} 个错词` : ''}。目标是高考阅读快速识义，不要求拼写。`,
    targetDate: settings.targetDate,
    daysRemaining: stats.daysRemaining,
    totalWords: stats.totalWords,
    learnedWords: stats.learnedWords,
    masteredWords: stats.masteredWords,
    remainingWords: stats.remainingWords,
    newWordIds: newIds,
    reviewWordIds: reviewIds,
    wrongWordIds: wrongIds,
    fuzzyWordIds: fuzzyIds,
    sentenceMeaningWordIds: sentenceIds,
    confusingWordIds: [],
    estimatedMinutes: Math.max(limits.minMin, Math.min(limits.maxMin, estimatedMin)),
    priorityReason: `${intensityLabel}模式：优先高频词 + 错词，以阅读识义为主`,
    motivationalMessage: `距目标还剩 ${stats.daysRemaining} 天，剩余 ${stats.remainingWords} 词，继续加油！`,
    createdBy: 'local_fallback',
    createdAt: now,
    updatedAt: now,
  }
}

// ── Enforce manual new-word count when allowAiAdjust is off ──────────────────
// If the user set manual mode AND allowAiAdjust===false, the AI result's
// newWordIds must be exactly dailyNewWords items (trim if too many, supplement
// from candidateNewWords if too few).
export function enforceUserNewWordCount(
  aiNewWordIds: string[],
  settings: MimoPlanSettings,
  candidateNewWords: CandidateWord[]
): string[] {
  if (settings.dailyNewWordsMode !== 'manual') return aiNewWordIds

  const target = settings.dailyNewWords
  // Always trim if AI returned more than target
  const trimmed = aiNewWordIds.length > target ? aiNewWordIds.slice(0, target) : aiNewWordIds

  if (settings.allowAiAdjust) {
    // Soft enforcement: accept AI result if it reached at least 80% of target
    if (trimmed.length >= Math.floor(target * 0.8)) return trimmed
  } else {
    // Strict enforcement: must match target exactly (if enough candidates)
    if (trimmed.length === target) return trimmed
  }

  // Supplement from candidates to reach target
  const existing = new Set(trimmed)
  const extra = candidateNewWords
    .filter(w => !existing.has(w.id))
    .slice(0, target - trimmed.length)
    .map(w => w.id)
  return [...trimmed, ...extra]
}

// ── Compute effective limits that respect user settings ───────────────────────
export interface IntensityLimit { newWords: number; reviewWords: number; minMin: number; maxMin: number }

// dailyNewTarget: pass the pre-computed target so AI validation uses the real value.
// For auto mode this is Math.ceil(remaining/days); for manual it's settings.dailyNewWords.
export function getEffectiveLimits(
  settings: MimoPlanSettings,
  dailyNewTarget?: number
): IntensityLimit {
  const base = INTENSITY_LIMITS[settings.dailyIntensity]
  const effectiveNew = settings.dailyNewWordsMode === 'manual'
    ? settings.dailyNewWords
    : (dailyNewTarget ?? base.newWords)  // use real target; fall back to intensity hint
  // dailyReviewLimit is a user ceiling; also cap by intensity
  const effectiveReview = Math.min(settings.dailyReviewLimit, base.reviewWords)
  return { ...base, newWords: effectiveNew, reviewWords: effectiveReview }
}

// ── Validate and clean AI response ────────────────────────────────────────────
export function validateAndCleanAiPlan(
  raw: Record<string, unknown>,
  validIds: Set<string>,
  limits: IntensityLimit
): Partial<MimoDailyPlan> | null {
  const filterIds = (arr: unknown, cap: number): string[] => {
    if (!Array.isArray(arr)) return []
    return (arr as string[]).filter(id => typeof id === 'string' && validIds.has(id)).slice(0, cap)
  }

  const newIds = filterIds(raw.newWordIds, limits.newWords)
  if (newIds.length === 0 && !raw.reviewWordIds) return null  // completely empty

  return {
    planTitle: typeof raw.planTitle === 'string' ? raw.planTitle : '今日阅读词汇计划',
    aiSummary: typeof raw.aiSummary === 'string' ? raw.aiSummary : '',
    newWordIds: newIds,
    reviewWordIds: filterIds(raw.reviewWordIds, limits.reviewWords),
    wrongWordIds: filterIds(raw.wrongWordIds, 20),
    fuzzyWordIds: filterIds(raw.fuzzyWordIds, 20),
    sentenceMeaningWordIds: filterIds(raw.sentenceMeaningWordIds, 15),
    confusingWordIds: filterIds(raw.confusingWordIds, 10),
    estimatedMinutes: typeof raw.estimatedMinutes === 'number' ? raw.estimatedMinutes : limits.minMin,
    priorityReason: typeof raw.priorityReason === 'string' ? raw.priorityReason : '',
    motivationalMessage: typeof raw.motivationalMessage === 'string' ? raw.motivationalMessage : '',
  }
}
